# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _ball_tree
else:
    import _ball_tree

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ball_tree.delete_SwigPyIterator

    def value(self):
        return _ball_tree.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _ball_tree.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _ball_tree.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _ball_tree.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _ball_tree.SwigPyIterator_equal(self, x)

    def copy(self):
        return _ball_tree.SwigPyIterator_copy(self)

    def next(self):
        return _ball_tree.SwigPyIterator_next(self)

    def __next__(self):
        return _ball_tree.SwigPyIterator___next__(self)

    def previous(self):
        return _ball_tree.SwigPyIterator_previous(self)

    def advance(self, n):
        return _ball_tree.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _ball_tree.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _ball_tree.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _ball_tree.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _ball_tree.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _ball_tree.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _ball_tree.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _ball_tree:
_ball_tree.SwigPyIterator_swigregister(SwigPyIterator)
class VectorDouble(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _ball_tree.VectorDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ball_tree.VectorDouble___nonzero__(self)

    def __bool__(self):
        return _ball_tree.VectorDouble___bool__(self)

    def __len__(self):
        return _ball_tree.VectorDouble___len__(self)

    def __getslice__(self, i, j):
        return _ball_tree.VectorDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ball_tree.VectorDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ball_tree.VectorDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ball_tree.VectorDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ball_tree.VectorDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ball_tree.VectorDouble___setitem__(self, *args)

    def pop(self):
        return _ball_tree.VectorDouble_pop(self)

    def append(self, x):
        return _ball_tree.VectorDouble_append(self, x)

    def empty(self):
        return _ball_tree.VectorDouble_empty(self)

    def size(self):
        return _ball_tree.VectorDouble_size(self)

    def swap(self, v):
        return _ball_tree.VectorDouble_swap(self, v)

    def begin(self):
        return _ball_tree.VectorDouble_begin(self)

    def end(self):
        return _ball_tree.VectorDouble_end(self)

    def rbegin(self):
        return _ball_tree.VectorDouble_rbegin(self)

    def rend(self):
        return _ball_tree.VectorDouble_rend(self)

    def clear(self):
        return _ball_tree.VectorDouble_clear(self)

    def get_allocator(self):
        return _ball_tree.VectorDouble_get_allocator(self)

    def pop_back(self):
        return _ball_tree.VectorDouble_pop_back(self)

    def erase(self, *args):
        return _ball_tree.VectorDouble_erase(self, *args)

    def __init__(self, *args):
        _ball_tree.VectorDouble_swiginit(self, _ball_tree.new_VectorDouble(*args))

    def push_back(self, x):
        return _ball_tree.VectorDouble_push_back(self, x)

    def front(self):
        return _ball_tree.VectorDouble_front(self)

    def back(self):
        return _ball_tree.VectorDouble_back(self)

    def assign(self, n, x):
        return _ball_tree.VectorDouble_assign(self, n, x)

    def resize(self, *args):
        return _ball_tree.VectorDouble_resize(self, *args)

    def insert(self, *args):
        return _ball_tree.VectorDouble_insert(self, *args)

    def reserve(self, n):
        return _ball_tree.VectorDouble_reserve(self, n)

    def capacity(self):
        return _ball_tree.VectorDouble_capacity(self)
    __swig_destroy__ = _ball_tree.delete_VectorDouble

# Register VectorDouble in _ball_tree:
_ball_tree.VectorDouble_swigregister(VectorDouble)
class VectorVectorDouble(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _ball_tree.VectorVectorDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ball_tree.VectorVectorDouble___nonzero__(self)

    def __bool__(self):
        return _ball_tree.VectorVectorDouble___bool__(self)

    def __len__(self):
        return _ball_tree.VectorVectorDouble___len__(self)

    def __getslice__(self, i, j):
        return _ball_tree.VectorVectorDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ball_tree.VectorVectorDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ball_tree.VectorVectorDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ball_tree.VectorVectorDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ball_tree.VectorVectorDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ball_tree.VectorVectorDouble___setitem__(self, *args)

    def pop(self):
        return _ball_tree.VectorVectorDouble_pop(self)

    def append(self, x):
        return _ball_tree.VectorVectorDouble_append(self, x)

    def empty(self):
        return _ball_tree.VectorVectorDouble_empty(self)

    def size(self):
        return _ball_tree.VectorVectorDouble_size(self)

    def swap(self, v):
        return _ball_tree.VectorVectorDouble_swap(self, v)

    def begin(self):
        return _ball_tree.VectorVectorDouble_begin(self)

    def end(self):
        return _ball_tree.VectorVectorDouble_end(self)

    def rbegin(self):
        return _ball_tree.VectorVectorDouble_rbegin(self)

    def rend(self):
        return _ball_tree.VectorVectorDouble_rend(self)

    def clear(self):
        return _ball_tree.VectorVectorDouble_clear(self)

    def get_allocator(self):
        return _ball_tree.VectorVectorDouble_get_allocator(self)

    def pop_back(self):
        return _ball_tree.VectorVectorDouble_pop_back(self)

    def erase(self, *args):
        return _ball_tree.VectorVectorDouble_erase(self, *args)

    def __init__(self, *args):
        _ball_tree.VectorVectorDouble_swiginit(self, _ball_tree.new_VectorVectorDouble(*args))

    def push_back(self, x):
        return _ball_tree.VectorVectorDouble_push_back(self, x)

    def front(self):
        return _ball_tree.VectorVectorDouble_front(self)

    def back(self):
        return _ball_tree.VectorVectorDouble_back(self)

    def assign(self, n, x):
        return _ball_tree.VectorVectorDouble_assign(self, n, x)

    def resize(self, *args):
        return _ball_tree.VectorVectorDouble_resize(self, *args)

    def insert(self, *args):
        return _ball_tree.VectorVectorDouble_insert(self, *args)

    def reserve(self, n):
        return _ball_tree.VectorVectorDouble_reserve(self, n)

    def capacity(self):
        return _ball_tree.VectorVectorDouble_capacity(self)
    __swig_destroy__ = _ball_tree.delete_VectorVectorDouble

# Register VectorVectorDouble in _ball_tree:
_ball_tree.VectorVectorDouble_swigregister(VectorVectorDouble)
class BallTree(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _ball_tree.BallTree_swiginit(self, _ball_tree.new_BallTree())

    def build(self, points):
        return _ball_tree.BallTree_build(self, points)

    def find_nearest(self, target):
        return _ball_tree.BallTree_find_nearest(self, target)
    __swig_destroy__ = _ball_tree.delete_BallTree

# Register BallTree in _ball_tree:
_ball_tree.BallTree_swigregister(BallTree)

